'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path');
test('numbered column settings renumber, preview, persist and reset without changing raw sorting',{skip:process.env.RUN_BROWSER_TESTS!=='1',timeout:90000},async t=>{
 const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright'),browser=await chromium.launch({headless:true,args:['--no-sandbox']});t.after(()=>browser.close());const html=await fs.readFile(path.join(__dirname,'../admin-audit.html'));
 for(const width of [1440,390])await t.test(String(width),async()=>{
 const orders={},formats={},widths={},errors=[],requests=[];let failSave=false;
 const root={id:'00000000-0000-4000-8000-000000000001',action:'upload_file',status:'completed',created_at:'2026-09-27T09:15:30.129Z',root_event_id:'1',event_count:'2',sub_event_count:'1',duration_ms:75427,operation_usage:{total_tokens:1234,cost_ils:0.12345}};
 const child={id:'2',operation_id:root.id,operation_action:root.action,created_at:root.created_at,kind:'provider_call_finished',status:'completed',sub_event_index:'1',sub_event_total:'1',operation_duration_ms:root.duration_ms,usage:{total_tokens:'9007199254740993',cost_ils:0.12345,status:'estimated'}};root.first_sub_event=child;
 async function open(){const context=await browser.newContext({viewport:{width,height:950},locale:'he-IL',timezoneId:'Asia/Jerusalem'}),page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>localStorage.setItem('bt_admin_token','mock-token'));
 await page.route('**/*',async route=>{const r=route.request(),u=new URL(r.url());if(u.hostname==='audit.test')return route.fulfill({contentType:'text/html',body:u.pathname.endsWith('.html')?html:''});requests.push(u);
 if(u.pathname.endsWith('/column-order'))return route.fulfill({json:{orders,widths,formats}});
 if(u.pathname.includes('/column-settings/')){if(failSave)return route.fulfill({status:503,json:{error:'unavailable'}});const mode=u.pathname.split('/').at(-1),body=r.postDataJSON();orders[mode]=body.order;formats[mode]=body.formats;return route.fulfill({json:{mode,...body}});}
 if(u.pathname.endsWith('/catalog'))return route.fulfill({json:{actions:[]}});if(u.pathname.endsWith('/operations'))return route.fulfill({json:{operations:[root],nextCursor:null}});if(u.pathname.endsWith('/events'))return route.fulfill({json:{events:[child],nextCursor:null}});throw Error('Unexpected '+u.pathname);
 });await page.goto('https://audit.test/admin-audit.html');await page.waitForFunction(()=>state.hasLoaded&&!state.loading&&columnOrdersLoaded);return {page,context};}
 let {page,context}=await open();const before=await page.locator('#audit-table thead th').evaluateAll(h=>h.map(x=>x.dataset.columnId));
 await page.locator('#open-column-settings').click();await page.locator('#settings-search').fill('עלות השלב');
 await page.locator('[data-setting-position="cost_ils"]').fill('1');await page.locator('[data-setting-position="cost_ils"]').press('Tab');
 assert.equal(await page.evaluate(()=>settingsDraft.order[0]),'cost_ils');const permutation=await page.evaluate(()=>settingsDraft.order);assert.equal(new Set(permutation).size,before.length);assert.deepEqual(permutation.slice(1),before.filter(k=>k!=='cost_ils'));
 await page.locator('[data-setting-type="cost_ils"]').selectOption('currency');await page.locator('[data-setting-decimals="cost_ils"]').fill('4');await page.locator('[data-setting-decimals="cost_ils"]').press('Tab');assert.equal(await page.locator('[data-settings-key="cost_ils"] .settings-preview').innerText(),'₪0.1235');
 await page.locator('#settings-search').fill('סה״כ טוקנים בשלב');await page.locator('[data-setting-type="total_tokens"]').selectOption('number');await page.locator('[data-setting-decimals="total_tokens"]').fill('0');await page.locator('[data-setting-decimals="total_tokens"]').press('Tab');assert.equal(await page.locator('[data-settings-key="total_tokens"] .settings-preview').innerText(),'9,007,199,254,740,993');
 failSave=true;await page.locator('#settings-save').click();await page.waitForFunction(()=>!settingsSaving);assert.ok(await page.locator('#settings-error').innerText());assert.equal(await page.locator('#settings-dialog').evaluate(x=>x.open),true);assert.deepEqual(await page.locator('#audit-table thead th').evaluateAll(h=>h.map(x=>x.dataset.columnId)),before);
 failSave=false;await page.locator('#settings-save').click();await page.waitForFunction(()=>!settingsDraft);assert.equal(await page.locator('#audit-table th').first().getAttribute('data-column-id'),'cost_ils');assert.equal(await page.locator('[data-field="cost_ils"]').innerText(),'₪0.1235');assert.equal(await page.locator('[data-field="total_tokens"]').innerText(),'9,007,199,254,740,993');assert.equal(await page.evaluate(()=>state.rows[0].first_sub_event.usage.cost_ils),0.12345);
 await page.locator('[data-column-sort="cost_ils"]').click();await page.waitForFunction(()=>!state.loading);assert.equal(requests.findLast(u=>u.pathname.endsWith('/operations')).searchParams.get('sort'),'cost_ils');
 await context.close();({page,context}=await open());assert.equal(await page.locator('#audit-table th').first().getAttribute('data-column-id'),'cost_ils');assert.equal(await page.locator('[data-field="cost_ils"]').innerText(),'₪0.1235');
 await page.locator('#open-column-settings').click();await page.locator('#settings-search').fill('עלות השלב');await page.locator('[data-setting-position="cost_ils"]').fill('999');await page.locator('[data-setting-position="cost_ils"]').press('Tab');assert.match(await page.locator('#settings-error').innerText(),/מיקום/);
 await page.locator('#settings-reset').click();await page.locator('#settings-cancel').click();assert.equal(await page.locator('#audit-table th').first().getAttribute('data-column-id'),'cost_ils');
 await page.locator('#events-tab').click();await page.waitForFunction(()=>state.mode==='events'&&!state.loading);assert.notEqual(await page.locator('#audit-table th').first().getAttribute('data-column-id'),'cost_ils');
 await page.locator('#operations-tab').click();await page.waitForFunction(()=>state.mode==='operations'&&!state.loading);await page.locator('#open-column-settings').click();await page.locator('#settings-reset').click();await page.locator('#settings-save').click();await page.waitForFunction(()=>!settingsDraft);assert.deepEqual(formats.operations,{});assert.deepEqual(await page.locator('#audit-table th').evaluateAll(h=>h.map(x=>x.dataset.columnId)),before);
 assert.deepEqual(errors,[]);await context.close();
 });
});
